### ISSUE TITLE
Bug: Sage Client: Mplayer updates to work on OSX

### ISSUE THREAD

**Issue by SageWizdom** [google/sagetv#109]
Mplayer on OSX does not display correctly with the new sage client.

I downloaded the new sage client.  I replaced the version of Mplayer with the old mplayer from v6.  While all the video plays, it plays in a new window.  The error displayed is...

------------------------------------------------------------------------------------
Error loading QuartzGFXCMD class, reverting to default rendering:java.lang.ClassNotFoundException: sage.miniclient.QuartzGFXCMD
java.lang.ClassNotFoundException: sage.miniclient.QuartzGFXCMD
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:171)
        at sage.miniclient.MiniClientConnection.GFXThread(MiniClientConnection.java:609)
        at sage.miniclient.MiniClientConnection.access$200(MiniClientConnection.java:18)
        at sage.miniclient.MiniClientConnection$4.run(MiniClientConnection.java:378)

------------------------------------------------------------------------------------
Exception getting video server params: java.lang.NoSuchMethodException: sage.miniclient.GFXCMD2.getServerVideoOutParams()

MPlayer was launched successfully
...
Ignoring resize command because it exceeds video dimensions rect=java.awt.Rectangle[x=0,y=0,width=720,height=480] videoDim=java.awt.Dimension[width=0,height=0]

**Comment by stuckless** [comment]
The Open Source MiniClient is not built to work with OSX.  It would require a specific build for OSX and I think it would have to be built on OSX hardware, which makes it unlikely to happen (at least from an automated point of view).  Even if the JAR was compatible, the underlying mplayer would have to be rebuild as well.

I'm not saying it's not going to happen, but I think that this would require someone to take on the full building and publishing of an OSX miniclient.

**Comment by Narflex** [comment]
Yup, Sean is right. :)

On Thu, Mar 24, 2016 at 4:27 AM, Sean Stuckless <notifications@github.com>
wrote:

> The Open Source MiniClient is not built to work with OSX. It would require
> a specific build for OSX and I think it would have to be built on OSX
> hardware, which makes it unlikely to happen (at least from an automated
> point of view). Even if the JAR was compatible, the underlying mplayer
> would have to be rebuild as well.
>
> I'm not saying it's not going to happen, but I think that this would
> require someone to take on the full building and publishing of an OSX
> miniclient.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/google/sagetv/issues/109#issuecomment-200796518>
>



-- 
Jeffrey Kardatzke
jkardatzke@google.com
Google, Inc.

**Comment by SageWizdom** [comment]
I was impressed with just how well it worked so far... all of the direct access to the server works, and other than playing video, seemed to be ok (not that I was looking in the log for errors).  Even the video displays correctly when pushed into mplayer (old mplayer) its just that mplayer is not captured and instead spawns a new window.  

Shesh... you guys are going to cause me to take up Java programming, and then who will I be able to give a hard time to!  Way at the bottom of the list, but I may try and run this in debug at least to see how many errors and issues there are.  If it is close, and just needs some updating (which was the impression I got) I might conceivable look into it at some point.  It would definitely need a peer review though.  (aka someone with an actual clue to check it over.)

**Comment by Narflex** [comment]
I'm always here to help. :)

On Thu, Mar 24, 2016 at 7:31 PM, SageWizdom <notifications@github.com>
wrote:

> I was impressed with just how well it worked so far... all of the direct
> access to the server works, and other than playing video, seemed to be ok
> (not that I was looking in the log for errors). Even the video displays
> correctly when pushed into mplayer (old mplayer) its just that mplayer is
> not captured and instead spawns a new window.
>
> Shesh... you guys are going to cause me to take up Java programming, and
> then who will I be able to give a hard time to! Way at the bottom of the
> list, but I may try and run this in debug at least to see how many errors
> and issues there are. If it is close, and just needs some updating (which
> was the impression I got) I might conceivable look into it at some point.
> It would definitely need a peer review though. (aka someone with an actual
> clue to check it over.)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/google/sagetv/issues/109#issuecomment-201112114>
>



-- 
Jeffrey Kardatzke
jkardatzke@google.com
Google, Inc.

**Comment by webernissle** [comment]
http://forums.sagetv.com/forums/showthread.php?t=62421 is a related forum thread on that. I think the best approach is to use the mplayer from homebrew osx, it will need a dedicated package for it is it will not be compatible with Linux.
